config/routes.rb
Rails.application.routes.draw do
 
 
  devise_for :users
  root to: "home#index"
  resources :users
  resources :rooms do
    get :search, on: :collection
    resources :books 
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :user
  belongs_to :room
   validates :check_in, presence: true
   validate :check_before_in
    def check_before_in
    errors.add(:check_in, "は今日以降のものを選択してください") if
    check_in < Date.today
    end
   validates :check_out, presence: true
   validate :check_before_out
    def check_before_out
    errors.add(:check_out, "はチェックイン以降のものを選択してください") if
    check_out < check_in
    end
   validates :people, numericality: true
end

app/models/room.rb
class Room < ApplicationRecord
    belongs_to :user
    attachment :room_image
    has_many :books
    validates :title, presence: true
   validates :address,  presence: true
   validates :price, numericality: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  attachment :profile_image
  has_many :rooms, dependent: :destroy
  has_many :books, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :configure_permitted_parameters, if: :devise_controller?
    private
    def configure_permitted_parameters
        devise_parameter_sanitizer.permit(:sign_up, keys: [:username])
        
    end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :authenticate_user!
  
  def index
    @books = Book.where(user_id: current_user.id)
    
   
    @name = current_user.username
  end

  def new
    @room = Room.find(params[:room_id])
    @book = Book.new
    @name = current_user.username
  end
  
  def create
    @book = Book.new(book_params)
      if @book.save
        redirect_to room_book_path(@book.room_id, @book)
      else
        #こちらの処理が実行されます。
        flash[:alert] = '全ての項目を正しく入力してください。'
        redirect_to room_path(@book.room_id)
      end
    
    @name = current_user.username
  end

  def edit
  end

  def show
    @book = Book.find(params[:id])
    @room = Room.find(params[:room_id])
    @price = (@book.check_out.to_date - @book.check_in.to_date).to_i * @room.price * @book.people
    @name = current_user.username
  end
  
  private
    def book_params
      params.require(:book).permit(:check_in, :check_out, :people, :room_id, :user_id)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    if user_signed_in?
    @name = current_user.username
    else
      @name = "ゲスト"
    end
  end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  before_action :authenticate_user!, expect: [:index]
  
  def index
   @rooms = Room.where('title LIKE ? or address LIKE ?', "%#{params[:search]}%", "%#{params[:search]}%")
   @name = current_user.username
  end

  def show
    @room = Room.find(params[:id])
    @name = current_user.username
    @book = Book.new
  end

  def new
    @room = Room.new
    @name = current_user.username
  end

  def create
    @room = Room.new(room_params)
    @room.user_id = current_user.id
    if @room.save
      flash[:notice] = "ルームを新規登録しました"
      redirect_to room_path(@room)
    else
      #こちらの処理が実行されます。
      render "new"
    end
    @name = current_user.username
  end

  def edit
    @room = Room.find(params[:id])
    @name = current_user.username
  end
  
  def update
    @room = Room.find(params[:id])
    @room.update(room_params)
    redirect_to room_path(@room)
    @name = current_user.username
  end
  
  def destroy
    room = Room.find(params[:id])
    room.destroy
    redirect_to rooms_path
    @name = current_user.username
  end
  
  private
  def room_params
    params.require(:room).permit(:title, :body, :price, :address, :room_image)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  before_action :authenticate_user!, expect: [:index]
  def index
    @users = User.all
    @name = current_user.username
  end

  def show
    @user = User.find(params[:id])
    @name = current_user.username
  end

  def edit
    @user = User.find(params[:id])
    @name = current_user.username
  end
  
  def update
    @user = User.find(params[:id])
    @user.update(user_params)
    redirect_to user_path(@user)
    @name = current_user.username
  end
  
  private
  def user_params
    params.require(:user).permit(:username, :email, :profile, :profile_image)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/edit.html.erb
<h1>Books#edit</h1>
<p>Find me in app/views/books/edit.html.erb</p>

app/views/books/index.html.erb
<section class="hero is-success">
  <div class="hero-body">
    <div class="container">
      <h1 class="title">
        予約済ルーム一覧
      </h1>
    </div>
  </div>
</section>
<section class="section">
  <div class="container">
    <div class="columns is-multiline">
      <% @books.each do |book| %>
        <% @rooms = Room.where(id: book.room_id) %>
        <% @rooms.each do |room| %>
        <div class="column is-4">
          <div class="card">
            <div class="card-image">
              <figure class="image is-4by3">
                <%= link_to room_path(room) do %>
                  <%= attachment_image_tag room, :room_image, class: "imags" %>
                <% end %>
              </figure>
            </div>
            <div class="card-content">
              <div class="media">
                <div class="media-content has-text-weight-semibold has-text-centered">
                    <%= room.title %><br>
                    チェックイン：<%= book.check_in %><br>
                    チェックアウト：<%= book.check_out %>
                  <%= link_to room_path(room), class: "panel-block" do %>
                  <button class="button is-fullwidth is-primary is-outlined">
                    <span class="panel-icon">
                      <i class="fas fa-book" aria-hidden="true"></i>
                    </span>
                    このルームを見る
                    </button>
                  <% end %>
                </div>
              </div>
              <div class="content has-text-right">
                <time><%= room.updated_at.strftime("%Y-%m-%d %H:%M") %></time>更新
              </div>
            </div>
          </div>
        </div>
        <% end %>
      <% end %>
    </div>
  </div>
</section>
</div>

app/views/books/new.html.erb
<article class="panel is-link check_par">
          <p class="panel-heading ">
            予約
          </p>
          <%= form_for [@room, @book] do |f| %>
          　<%= f.hidden_field :room_id, value: @room.id %>
            <%= f.hidden_field :user_id, value: current_user.id %>
            <div class="field">
              <p class="label">Price</p>
              <div class="control">
                ¥<%= @room.price %>/人
              </div>
            </div>
            <div class="field">
              <%= f.label :check_in, class: "label" %>
              <div class="control has-icons-left has-icons-right">
                <%= f.date_field :check_in, class: "input" %>
              </div>
            </div>
            
            <div class="field">
              <%= f.label :check_out, class: "label" %>
              <div class="control has-icons-left has-icons-right">
                <%= f.date_field :check_out, class: "input" %>
              </div>
            </div>
            
            <div class="field">
              <%= f.label :people, class: "label" %>
              <div class="control has-icons-left has-icons-right">
               <%= f.number_field :people, class: "input" %>
              </div>
            </div>
            
            <div class="field is-grouped is-grouped-centered">
              <div class="control">
                <%= f.submit '確定',class: " button is-link" %>
              </div>
            </div>
            <% end %>
        </article>

app/views/books/show.html.erb
<div class="book_show_main">
<div class="column">
    <article class="panel is-link">
      <p class="panel-heading ">
        予約内容確認
      </p>
         <div class="field check_book check_top">
          <p class="label">ルーム名</p>
          <div class="control has-icons-left has-icons-right">
           <%= @room.title %>
          </div>
        </div>
        <div class="field check_book">
          <p class="label">料金</p>
          <div class="control">
            ¥<%= @room.price %>/日
          </div>
        </div>
        <div class="field check_book">
          <p class="label">チェックイン日</p>
          <div class="control has-icons-left has-icons-right">
            <%= @book.check_in %>
          </div>
        </div>
        
        <div class="field check_book">
          <p class="label">チェックアウト日</p>
          <div class="control has-icons-left has-icons-right">
            <%= @book.check_out %>
          </div>
        </div>
        
        <div class="field check_book">
          <p class="label">人数</p>
          <div class="control has-icons-left has-icons-right">
           <%= @book.people %>人
          </div>
        </div>
        <div class="field check_book las">
          <p class="label">合計金額</p>
          <div class="control has-icons-left has-icons-right">
           ¥<%= @price %>
          </div>
        </div>
        <div class="field">
          <p class="label">　</p>
          <div class="control has-icons-left has-icons-right">
          </div>
        </div>
        <div class="button-container">
        <%= link_to "ホーム画面へ", root_path, class: "button is-success is-fullwidth" %>
        </div>
    </article>
</div>
</div>

app/views/home/index.html.erb
<div class="top">
    <div class="indexTopWrapper">
        <div class="container">
            <div class="formContainer">
            <h1>Potepan Shareでまだ体験したことのない旅をしよう</h1>
            <p>エリアorキーワード</p>
            <div class="container-form">
                <%= form_tag(rooms_path,:method => 'get') do %>
                <%= text_field_tag :search,"", class: "input block is-normal"  %>
                </br><%= submit_tag 'Search', :title => nil, class: "formbottun button block is-info is-fullwidth"  %>
                <% end %>
            </div>
            </div>
        </div>
    </div>
</div>
<div class="middle">
    <div class=recomendContainer>
        <h1>おすすめエリア</h1>
        <ul class="area-imgs">
            <%= link_to rooms_path(search: "東京") do %> 
            <li><span>東京</span><a class="indexTokyo recomendLink"><img class="areaImg" src="https://presite-potepancamp-rails-02.herokuapp.com/assets/img_tokyo.jpg"></a></li>
            <% end %>
            <%= link_to rooms_path(search: "大阪") do %> 
               <li><span>大阪</span><img class="areaImg" src="https://presite-potepancamp-rails-02.herokuapp.com/assets/img_osaka.jpg"></a></li>
                
            <% end %>
            <%= link_to rooms_path(params:{search: "京都"}) do %> 
            <li><span>京都</span><a class="indexKyoto recomendLink"><img class="areaImg" src="https://presite-potepancamp-rails-02.herokuapp.com/assets/img_kyoto.jpg"></a></li>
            <% end %>
            <%= link_to rooms_path(search: "札幌") do %> 
            <li><span>札幌</span><a class="indexSapporo recomendLink"><img class="areaImg" src="https://presite-potepancamp-rails-02.herokuapp.com/assets/img_sapporo.jpg"></a></li>
            <% end %>
        </ul>
        
    </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Poteshare</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/lib..." integrity="sha256-UzFD2WYH2U1dQpKDjjZK72VtPeWP50NoJjd26rnAdUI=" crossorigin="anonymous" />
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://code.jquery.com/jquery-3.4.1.js"></script>
    <script src="./practice.js"></script>
    <!-- drawer.css -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/drawer/3.2.2/css/drawer.min.css">
    <!-- jquery &amp; iScroll -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/iScroll/5.2.0/iscroll.min.js"></script>
    <!-- drawer.js -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/drawer/3.2.2/js/drawer.min.js"></script>
  </head>
  
  <body>
  <header class="drawer drawer--right"  role="banner">
    <div class="header-left">
      <div class="header-logo">
        <%= link_to root_path, class: "navbar-item" do %>
          <h1 class="title is-4" style="fony-family: cursive;">poteshare</h1>
        <% end %>
      </div>
      <div class="header-form">
        <%= form_tag(rooms_path,:method => 'get') do %>
          <%= text_field_tag :search,"", class: "input block is-normal", placeholder: "エリアorキーワード" %>
        <% end %>
      </div>
    </div>
    <div class="hedaer-right">
    <% if user_signed_in? %>
      <nav class="navbar is-black" role="navigation" aria-label="dropdown navigation">
        <div class="navbar-item has-dropdown is-hoverable">
          <a class="navbar-link">
            <%= @name %>
          </a>
          <div class="navbar-dropdown is-right">
            <a class="navbar-item">
              <%= link_to "ルーム登録", new_room_path, class: "button is-fullwidth" %>
            </a>
            <a class="navbar-item">
              <%= link_to "ルーム一覧", rooms_path, class: "button is-fullwidth" %>
            </a>
            <a class="navbar-item">
              <%= link_to "予約済ルーム一覧", room_books_path(current_user), class: "button is-fullwidth" %>
            </a>
            <a class="navbar-item">
              <%= link_to "ログアウト", destroy_user_session_path, method: :delete, class: "button is-fullwidth" %>
            </a>
            <a class="navbar-item">
              <%= link_to "マイページ", user_path(current_user), class: "button is-fullwidth" %>
            </a>
          </div>
        </div>
      </nav>
      
    <% else %>
      
       
        <%= link_to "ログイン", new_user_session_path, class: "button is-warning is-light" %>
        <%= link_to "新規登録", new_user_registration_path, class: "button is-warning is-light" %>
      
    <% end %>
    </div>
  </header>
  
    
  
  <main role="main">
    <% if flash[:notice] %>
      <div class="notification is-info">
        <p class="notice"><%= notice %></p>
      </div>
    <% end %>
    
    <% if flash[:alert] %>
      <div class="notification is-danger">
        <p class="alert"><%= alert %></p>
      </div>
    <% end %>
     <%= yield %>
    <!-- Page content -->
  </main>
  <footer class="footer">
  <div class="content has-text-centered">
    <p>
      ©️2021 ryosuke onishi
    </p>
  </div>
</footer>
</body>
</html>
 <script>
$(document).ready(function() {
  $('.drawer').drawer();
});
</script>

app/views/rooms/edit.html.erb
<section class="hero is-success">
  <div class="hero-body">
    <div class="container">
      <h1 class="title">
        ルーム新規登録
      </h1>
    </div>
  </div>
</section>
<div class="card">
  <div class="card-content">
    <div class="content">
          <%= form_for @room do |f| %>  
            <div class="field">
              <label class="label">ルーム名</label>
              <div class="control">
                  <%= f.text_field :title, class: "input"  %>
              </div>
            </div>
            
            <div class="field">
              <label class="label">ルーム詳細</label>
              <div class="control ">
                <%= f.text_area :body, class: "textarea"  %>
              </div>
            </div>
            
            <div class="field">
              <label class="label">料金</label>
              <div class="control ">
                <%= f.number_field :price, class: "input"  %>
              </div>
            </div>
            <div class="field">
              <label class="label">住所</label>
              <div class="control">
                <%= f.text_field :address, class: "input"  %>
              </div>
            </div>
            
            <div class="field">
              <label class="label">イメージ写真</label>
              <div class="control has-icons-left has-icons-right">
                <%= f.attachment_field :room_image %>
              </div>
            </div>
            <div class="field is-grouped is-grouped-centered">
              <div class="control">
                <%= f.submit '確定',class: " button is-link" %>
              </div>
            </div>
            <% end %>
    </div>
  </div>
</div>

app/views/rooms/index.html.erb
<section class="hero is-success">
  <div class="hero-body">
    <div class="container">
      <h1 class="title">
        ルーム一覧
      </h1>
    </div>
  </div>
</section>
<section class="section">
  <div class="container">
    <div class="columns is-multiline">
      <% @rooms.each do |room| %>
        <div class="column is-4">
          <div class="card">
            <div class="card-image">
              <figure class="image is-4by3">
                <%= link_to room_path(room) do %>
                  <%= attachment_image_tag room, :room_image, class: "imags" %>
                <% end %>
              </figure>
            </div>
            <div class="card-content">
              <div class="media">
                <div class="media-content has-text-weight-semibold has-text-centered">
                    <%= room.title %>
                  <%= link_to room_path(room), class: "panel-block" do %>
                  <button class="button is-fullwidth is-primary is-outlined">
                    <span class="panel-icon">
                      <i class="fas fa-book" aria-hidden="true"></i>
                    </span>
                    このルームを見る
                    </button>
                  <% end %>
                </div>
              </div>
              <div class="content has-text-right">
                <time><%= room.updated_at.strftime("%Y-%m-%d %H:%M") %></time>更新
              </div>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</section>
</div>

app/views/rooms/new.html.erb
<section class="hero is-success">
  <div class="hero-body">
    <div class="container">
      <h1 class="title">
        ルーム新規登録
      </h1>
    </div>
  </div>
</section>
<%= render "shared/error", obj: @room %>
<div class="card">
  <div class="card-content">
    <div class="content">
          <%= form_for @room do |f| %>
            <div class="field">
              <label class="label">ルーム名</label>
              <div class="control">
                  <%= f.text_field :title, class: "input", placeholder: "ルーム名"  %>
              </div>
            </div>
            
            <div class="field">
              <label class="label">ルーム詳細</label>
              <div class="control ">
                <%= f.text_area :body, class: "textarea",placeholder: "ルーム詳細情報"  %>
              </div>
            </div>
            
            <div class="field">
              <label class="label">料金</label>
              <div class="control ">
                <%= f.number_field :price, class: "input", placeholder: "ルーム料金"  %>
              </div>
            </div>
            <div class="field">
              <label class="label">住所</label>
              <div class="control">
                <%= f.text_field :address, class: "input", placeholder: "ルームの住所"  %>
              </div>
            </div>
            
            <div class="field">
              <label class="label">イメージ写真</label>
              <div class="control has-icons-left has-icons-right">
                <%= f.attachment_field :room_image, fallback: "no-image.png" %>
              </div>
            </div>
            <div class="field is-grouped is-grouped-centered">
              <div class="control">
                <%= f.submit '確定',class: " button is-link" %>
              </div>
            </div>
            <% end %>
    </div>
  </div>
</div>

app/views/rooms/show.html.erb
<section class="hero is-success">
  <div class="hero-body">
    <div class="container">
      <h1 class="title">
        ルーム詳細
      </h1>
    </div>
  </div>
</section>
<%= flash[:alret] %>
<section class="section">
  <div class="container">
    <div class="columns is-centered">
      <div class="column is-7">
        <div class="card">
          <div class="card-image">
            <figure class="image is-4by3">
              <%= attachment_image_tag @room, :room_image %>
            </figure>
          </div>
          <div class="card-content">
            <div class="media">
              <div class="media-content">
                <p class="title is-4"><%= @room.title %></p>
              </div>
            </div>
            <div class="content">
              <table class="table is-narrow">
                <tr>
                  <th><%= @room.title %></th>
                </tr>
                <tr>
                  <td><%= simple_format @room.address %></td>
                </tr>
                <tr>
                  <td><%= simple_format @room.body %></td>
                </tr>
              </table>
              <% if @room.user.id == current_user.id %>
                <%= link_to "編集画面へ", edit_room_path(@room), class: "button is-success" %>
                <%= link_to "削除", room_path(@room), method: :delete, data: {confirm: "削除しますか？"}, class: "button is-success" %>
              <% end %>
            </div>
          </div>
        </div>
      </div>

      <div class="column is-4">
        <article class="panel is-link check_par">
          <p class="panel-heading ">
            予約
          </p>
          <%= form_for [@room, @book] do |f| %>
          　<%= f.hidden_field :room_id, value: @room.id %>
            <%= f.hidden_field :user_id, value: current_user.id %>
            <div class="field">
              <p class="label">Price</p>
              <div class="control">
                ¥<%= @room.price %>/人
              </div>
            </div>
            <div class="field">
              <%= f.label :check_in, class: "label" %>
              <div class="control has-icons-left has-icons-right">
                <%= f.date_field :check_in, class: "input" %>
              </div>
            </div>
            
            <div class="field">
              <%= f.label :check_out, class: "label" %>
              <div class="control has-icons-left has-icons-right">
                <%= f.date_field :check_out, class: "input" %>
              </div>
            </div>
            
            <div class="field">
              <%= f.label :people, class: "label" %>
              <div class="control has-icons-left has-icons-right">
               <%= f.number_field :people, class: "input" %>
              </div>
            </div>
            
            <div class="field is-grouped is-grouped-centered">
              <div class="control">
                <%= f.submit '確定',class: " button is-link" %>
              </div>
            </div>
            <% end %>
        </article>
        <article class="panel is-link">
          <p class="panel-heading ">
            このROOMのホストは<%= @room.user.username %>です。
          </p>
            <div class="field block">
              <p class="label">Profile</p>
              <div class="control has-icons-left has-icons-right">
              <%= @room.user.profile %>
              </div>
            </div>
            
            <div class="field">
              <%= link_to user_path(@room.user), class: "panel-block" do %>
              <button class="button is-fullwidth is-primary is-outlined">
                    <span class="panel-icon">
                      <i class="fas fa-book" aria-hidden="true"></i>
                    </span>
                    このホストを見る
                    </button>
                  <% end %>
              
            </div>
            
            <div class="field">
              
              
            </div>
        </article>
      </div>
    </div>
  </div>
</section>

app/views/shared/_error.html.erb
<% if obj.errors.any? %>
    <% obj.errors.full_messages.each do |message| %>
        <ul>
            <li><%= message %></p>    
        </ul>
    <% end %>
<% end %>

app/views/users/edit.html.erb
<%= form_for @user do |f| %>
<div class="card-header bg-transparent font-weight-bold">
    <h1 class="loginTitle font-weight-bold">編集</h1>
    </div>
<div class="card-body loginContainer">

<div class="field">
<%= f.label :username %><br />
<%= f.text_field :username %>

<div class="field">
<%= f.label :email %><br />
<%= f.text_field :email %>
</div>

<div class="field">
<%= f.label :profile %><br />
<%= f.text_field :profile %>
</div>

<div class="field">
<%= f.label :profile %><br />
<%= f.text_area :profile %>
</div>

<div class="field">
<%= f.label :profile_image %><br />
<%= f.attachment_field :profile_image, fallback: "no-image.png" %>
</div>

<div class="actions">
<%= f.submit "更新" %>
</div>

<% end %>

 <!--link_to "アカウント", password_path(current_user), class: "button is-warning is-light" %>-->

app/views/users/index.html.erb
<h1>Users#index</h1>
<p>Find me in app/views/users/index.html.erb</p>

<% @users.each do |user| %>
<%= link_to user_path(user) do %>
<%= attachment_image_tag user, :profile_image, fallback: "no-image.png" %>
<% end %>
<%= link_to user.username, user_path(user) %>

<% end %>

app/views/users/show.html.erb
<div class="user-main">
<h1 class="user-title">マイページ</h1>

<div class="card">
  <div class="card-content">
    <div class="content">
        <table class="table is-fullwidth">
          <thead>
            <tr>
              <th>アカウント</th>
              <th></th>
            </tr>
          </thead>
          <tbody>
            <tr>
              <th>メールアドレス</th>
              <td><%= @user.email %></td>
            </tr>
            <tr>
              <th>パスワード</th>
              <td>＊＊＊＊＊＊＊＊＊＊</td>
            </tr>
            <tr>
              <th>プロフィール</th>
              <td><%= @user.profile %></td>
            </tr>
          </tbody>
        </table>


<%= link_to "編集", edit_user_path(@user), class: "button is-primary" %>

    </div>
  </div>
</div>


<section class="section">
  <div class="container">
    <div class="columns is-multiline">
      <% @user.rooms.each do |room| %>
        <div class="column is-4">
          <div class="card">
            <div class="card-image">
              <figure class="image is-4by3">
                <%= link_to room_path(room) do %>
                  <%= attachment_image_tag room, :room_image, class: "imags" %>
                <% end %>
              </figure>
            </div>
            <div class="card-content">
              <div class="media">
                <div class="media-content">
                  <%= link_to room_path(room), class: "panel-block" do %>
                    <span class="panel-icon">
                      <i class="fas fa-book" aria-hidden="true"></i>
                    </span>
                    このルームを見る
                  <% end %>
                  <% if @user.id == current_user.id %>
                    <%= link_to edit_room_path(room), class: "panel-block" do %>
                      <span class="panel-icon">
                        <i class="fas fa-edit"></i>
                      </span>
                      このルームを編集する
                    <% end %>
                    <%= link_to room_path(room), method: :delete, data: {confirm: "削除しますか？"}, class: "panel-block" do %>
                      <span class="panel-icon">
                        <i class="fas fa-trash"></i>
                      </span>
                      このルームを削除する
                    <% end %>
                  <% end %>
                </div>
              </div>
              <div class="content">
                <time><%= room.updated_at.strftime("%Y-%m-%d %H:%M") %></time>更新
              </div>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</section>